TSVSite/Models/BusinessLogicModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TSVSite.Models;
using TSVSite.ef;

namespace TSVSite.Models
{
    public class BusinessLogicModel
    {
        public bool AddContactUs(ContactUsModel objContactUsModel)
        {
            try
            {
                CSDBEntities objCSDBEntities = new CSDBEntities();
                tbl_ContactUS objtblContactUS = new tbl_ContactUS();
                objtblContactUS.Name = objContactUsModel.Name;
                objtblContactUS.MobileNo = objContactUsModel.MobileNo;
                objtblContactUS.Email= objContactUsModel.Email;
                objtblContactUS.BusinessWebsite = objContactUsModel.BusinessWebsite;
                objtblContactUS.Subject = objContactUsModel.Subject;
                objtblContactUS.BusinessMessage = objContactUsModel.BusinessMessage;
                objCSDBEntities.tbl_ContactUS.Add(objtblContactUS);
                objCSDBEntities.SaveChanges();
                return true;
            }
            catch(Exception ex)
            {
                return false;
            }
            finally
            {

            }
        }
    }
}

TSVSite/Models/ContactUsModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TSVSite.Models
{
    public class ContactUsModel
    {

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [DisplayName("Name")]
        [Required(ErrorMessage="Please Enter Name")]
        public string Name { get; set;}

        [DisplayName("Mobile No")]
        [Required(ErrorMessage = "Please Enter Mobile No")]
        public string MobileNo { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Please Enter Email")]
        public string Email { get; set; }

        [DisplayName("Subject")]
        [Required(ErrorMessage = "Please Enter Subject")]
        public string Subject { get; set; }

        [DisplayName("Description")]
        [Required(ErrorMessage = "Please Enter Description")]
        public string BusinessMessage { get; set; }

        [DisplayName("Business Website")]
        public string BusinessWebsite { get; set; }
    }
}

TSVSite/Controllers/BusinessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TSVSite.Controllers
{
    public class BusinessController : Controller
    {
        // GET: Business
        public ActionResult Login()
        {
            return View();
        }

        public ActionResult BusinessQuery()
        {
            return View();
        }

        public ActionResult BusinessQueryDetail()
        {
            return View();
        }
    }
}

TSVSite/Controllers/CSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TSVSite.Models;

namespace TSVSite.Controllers
{
    public class CSController : Controller
    {
        BusinessLogicModel objBusinessLogicModel;
        // GET: CS
        public ActionResult Home()
        {
            return View();
        }
        public ActionResult AboutUs()
        {
            return View();
        }
        public ActionResult Services()
        {
            return View();
        }
        public ActionResult ContactUs()
        {
            ViewBag.ShowDiv = false;
            return View();
        }
        [HttpPost]
        public ActionResult ContactUs(ContactUsModel objContactUsModel)
        {
            ViewBag.ShowDiv = false;
            try
            {
                if (ModelState.IsValid)
                {
                    objBusinessLogicModel = new BusinessLogicModel();
                    if (objBusinessLogicModel.AddContactUs(objContactUsModel))
                    {
                        ModelState.Clear();
                        ViewBag.ShowDiv = true;
                        return View();
                    }
                    else
                    {
                        return View();
                    }
                }
                else
                {
                    return View();
                }
            }
            catch(Exception ex)
            {
                return View();
            }
            finally
            {
                objBusinessLogicModel = null;
            }
        }
    }
}

TSVSite/Controllers/RNDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TSVSite.Controllers
{
    public class RNDController : Controller
    {
        // GET: RND
        public ActionResult ImageFadeOut()
        {
            return View();
        }
    }
}

TSVSite/Views/CS/AboutUs.cshtml
@{
    ViewBag.Title = "AboutUs";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<div id="breadcrumb">
    <div class="container">
        <div class="breadcrumb">
            <li>@Html.ActionLink("Home", "Home", "CS")</li>
            <li>About Us</li>
        </div>
    </div>
</div>

<div class="aboutus">
    <div class="container">

        @*<div class="col-md-7 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">*@
            <div class="col-md-7">
             <img src=" ~/images/7.jpg" class="img-responsive">
            <h4>Who we are</h4>
            <p>
                Connecting solution has been founded in early 2017 with the team of young and innovative professional who are having 10+ Years of expertise into enabling, implementing & plugging the Digital Payment Solution, API Integration, Reconciliation and Business Automation.
            </p>
            <p>
                We understand the pain of client who is into online business and having less knowledge of Digital Payment Solution, API Integration, Reconciliation and Business Automation. We provide the solution to increase the business revenue for our client.
            </p>
        </div>
        @*<div class="col-md-5 wow fadeInDown" >*@@*data-wow-duration="1000ms" data-wow-delay="600ms">*@
            <div class="col-md-5">
    <div class=" skill">
                <h4>Our Goal</h4>
                <p>To build a rapidly growing organization using innovations to empower client, by simplifying payments acceptance and by providing enhanced value additions for better business growth.</p>
            </div>
            <div class="skill">
                <h4>Our Vision</h4>
                <p>To be a valuable asset for our client and play a major role in Digital Payment Solution, API Integration, Reconciliation and Business Automation for our client.</p>
            </div>
            <div class="skill">
                <h4>Our Philosophy</h4>
                <p>We consider our employees as the most valuable assets of the company. We believe that employees working in our organization are an asset with unlimited potential when given an opportunity for growth and development.</p>
            </div>
        </div>
    </div>
</div>
@*<div class="our-team">
        <div class="container">
            <h3>Our Team</h3>
            <div class="text-center">
                <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                    <img src="~/images/services/1.jpg" alt="">
                    <h4>John Doe</h4>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing eil sed deiusmod tempor</p>
                </div>
                <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                    <img src="~/images/services/2.jpg" alt="">
                    <h4>John Doe</h4>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing eil sed deiusmod tempor</p>
                </div>
                <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="900ms">
                    <img src="~/images/services/3.jpg" alt="">
                    <h4>John Doe</h4>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing eil sed deiusmod tempor</p>
                </div>
            </div>
        </div>
    </div>*@

TSVSite/Views/CS/ContactUs.cshtml
@model TSVSite.Models.ContactUsModel
@{
    ViewBag.Title = "ContactUs";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<div id="breadcrumb">
    <div class="container">
        <div class="breadcrumb">
            <li>@Html.ActionLink("Home", "Home", "CS")</li>
            <li>Contact</li>
        </div>
    </div>
</div>

@*<div class="map">
    <div id="google-map" data-latitude="40.713732" data-longitude="-74.0092704"></div>
</div>*@

<section id="contact-page">
    <div class="container">
        <div class="center">
            <h2>Drop Your Message</h2>
            <p>Kindly share your business requirement with us.</p>
        </div>
        <div class="row">
            <div class="status alert alert-success" style="display: none"></div>
            <div class="col-md-6 col-md-offset-3">
                <div id="sendmessage" style="display: @(ViewBag.ShowDiv ? "block" : "none")">Your message has been sent. Thank you!</div>
                <div id="errormessage"></div>
                @using (Html.BeginForm("ContactUs", "CS", FormMethod.Post, new { autocomplete="off"}))
                {
                    @*<div class="form-group">
                        @Html.DisplayNameFor(m=>m.Name)
                        @Html.TextBox("txtName1", null, new { @class = "form-control", placeholder = "Your Name", data_rule = "minlen:4", data_msg = "Please enter at least 4 chars", required = "required" })
                    </div>*@

                    <div class="form-group">
                        @Html.LabelFor(m => m.Name,new {style= "color:#FF6347;" })
                        @Html.TextBoxFor(m => m.Name, "Anil Shah",new {@class= "form-control",placeholder = "Your Name", data_rule = "minlen:4", data_msg = "Please enter at least 4 chars", required = "required" })
                        @*<input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />*@
                        @*<div class="validation"></div>*@
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.MobileNo, new { style = "color:#FF6347;" })
                        @Html.TextBoxFor(m => m.MobileNo, "9819448145", new { @class = "form-control", placeholder = "Your Mobile Number", data_rule = "minlen:4", data_msg = "Please enter valid mobile no", required = "required" })
                        @*<input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />*@
                        <div class="validation"></div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Email, new { style = "color:#FF6347;" })
                        @Html.TextBoxFor(m => m.Email, "anil.shah@udio.in", new { @class = "form-control", placeholder = "Your Email", data_rule = "email", data_msg = "Please enter valid email", required = "required" })
                        @*<input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />*@
                        <div class="validation"></div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.BusinessWebsite, new { style = "color:#FF6347;" })
                        @Html.TextBoxFor(m => m.BusinessWebsite, "http://www.udio.in", new { @class = "form-control", placeholder = "Your Business Website" })
                        @*<input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />*@
                        <div class="validation"></div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Subject, new { style = "color:#FF6347;" })
                        @Html.TextBoxFor(m => m.Subject, "My business requirement", new { @class = "form-control", placeholder = "Subject", data_rule = "minlen:8", data_msg = "Please enter at least 8 chars of subject", required = "required" })
                        @*<input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:8" data-msg="Please enter at least 8 chars of subject" />*@
                        <div class="validation"></div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.BusinessMessage, new { style = "color:#FF6347;" })
                        @Html.TextAreaFor(m => m.BusinessMessage, new { @class = "form-control", placeholder = "Message", rows = "7", data_rule = "minlen:8", data_msg = "Please write something for us", required = "required" })
                        @*<textarea class="form-control" name="message" rows="7" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>*@
                        <div class="validation"></div>
                    </div>
                    <div class="text-center">
                <button type="submit" name="submit" class="btn btn-primary btn-lg" required="required" >Submit Message</button></div>
              
                }
            </div>
        </div><!--/.row-->
    </div><!--/.container-->
</section><!--/#contact-page-->

TSVSite/Views/CS/Home.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<section id="main-slider" class="no-margin">
    <div class="carousel slide">
        <div class="carousel-inner">
            <div class="item active" style="background-image: url(/images/slider/bg1.jpg)">
                <div class="container">
                    <div class="row slide-margin">
                        <div class="col-sm-6">
                            <div class="carousel-content">
                                <h2 class="animation animated-item-1">Welcome <span>Company</span></h2>
                                <p class="animation animated-item-2">Accusantium doloremque laudantium totam rem aperiam, eaque ipsa...</p>
                                <a class="btn-slide animation animated-item-3" href="#">Read More</a>
                            </div>
                        </div>

                        <div class="col-sm-6 hidden-xs animation animated-item-4">
                            <div class="slider-img">
                                <img src="~/images/slider/img3.png" class="img-responsive">
                            </div>
                        </div>

                    </div>
                </div>
            </div><!--/.item-->
        </div><!--/.carousel-inner-->
    </div><!--/.carousel-->
</section><!--/#main-slider-->

<div class="feature">
    <div class="container">
        <div class="text-center">
            <div class="col-md-3">
                <div class="hi-icon-wrap hi-icon-effect">
                    <i class="fa fa-book"></i>
                    <h2><a href="@Url.Action("Services", "CS",null)#businesspaymentsolution">Payment Solution</a></h2>
                    @*<p>Quisque eu ante at tortor imperdiet gravida nec sed turpis phasellus.</p>*@
                </div>
            </div>
            <div class="col-md-3">
                <div class="hi-icon-wrap hi-icon-effect">
                    <i class="fa fa-laptop"></i>
                    <h2><a href="@Url.Action("Services", "CS",null)#APIPlugin">Payment API Plug in</a></h2>
                    @*<p>Quisque eu ante at tortor imperdiet gravida nec sed turpis phasellus.</p>*@
                </div>
            </div>
            <div class="col-md-3">
                <div class="hi-icon-wrap hi-icon-effect">
                    <i class="fa fa-heart-o"></i>
                    <h2><a href="@Url.Action("Services", "CS",null)#reconciliation">Reconciliation</a></h2>
                    @*@Html.ActionLink("Reconciliation", "Services%23reconciliation", "CS", null, //   Route args if needed; null if not.
new { @style = "color:red;" })*@
                    @*<p>Quisque eu ante at tortor imperdiet gravida nec sed turpis phasellus.</p>*@
                </div>
            </div>
            <div class="col-md-3">
                <div class="hi-icon-wrap hi-icon-effect">
                    <i class="fa fa-cloud"></i>
                    <h2><a href="@Url.Action("Services", "CS",null)#automation">Business Automation</a></h2>
                   
                    @*<p>Quisque eu ante at tortor imperdiet gravida nec sed turpis phasellus.</p>*@
                </div>
            </div>
        </div>
    </div>
</div>

@*<div class="about">
    <div class="container">
        <div class="col-md-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
            <h2>about us</h2>
            <img src="~/images/6.jpg" class="img-responsive" />
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat
                libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
                libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
                libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
            </p>
        </div>

        <div class="col-md-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
            <h2>Template built with Twitter Bootstrap</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat
                libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
                libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
                libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat
                libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
                libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
                libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
            </p>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat libero, pulvinar tincidunt leo consectetur eget.
                Curabitur lacinia pellentesque libero, pulvinar tincidunt leo consectetur eget.
                Curabitur lacinia pellentesque libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
            </p>
        </div>
    </div>
</div>*@

@*<div class="lates">
    <div class="container">
        <div class="text-center">
            <h2>Lates News</h2>
        </div>
        <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
            <img src="~/images/4.jpg" class="img-responsive" />
            <h3>Template built with Twitter Bootstrap</h3>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat
                libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
                libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
                libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
            </p>
        </div>

        <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
            <img src="~/images/4.jpg" class="img-responsive" />
            <h3>Template built with Twitter Bootstrap</h3>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat
                libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
                libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
                libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
            </p>
        </div>

        <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="900ms">
            <img src="~/images/4.jpg" class="img-responsive" />
            <h3>Template built with Twitter Bootstrap</h3>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat
                libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
                libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
                libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
            </p>
        </div>
    </div>
</div>*@

@*<section id="partner">
    <div class="container">
        <div class="center wow fadeInDown">
            <h2>Our Partners</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut <br> et dolore magna aliqua. Ut enim ad minim veniam</p>
        </div>

        <div class="partners">
            <ul>
                <li> <a href="#"><img class="img-responsive wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms" src="~/images/partners/partner1.png"></a></li>
                <li> <a href="#"><img class="img-responsive wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms" src="~/images/partners/partner2.png"></a></li>
                <li> <a href="#"><img class="img-responsive wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="900ms" src="~/images/partners/partner3.png"></a></li>
                <li> <a href="#"><img class="img-responsive wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="1200ms" src="~/images/partners/partner4.png"></a></li>
                <li> <a href="#"><img class="img-responsive wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="1500ms" src="~/images/partners/partner5.png"></a></li>
            </ul>
        </div>
    </div><!--/.container-->
</section><!--/#partner-->*@

@*<section id="conatcat-info">
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <div class="media contact-info wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                    <div class="pull-left">
                        <i class="fa fa-phone"></i>
                    </div>
                    <div class="media-body">
                        <h2>Have a question or need a custom quote?</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation +0123 456 70 80</p>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/.container-->
</section><!--/#conatcat-info-->*@

TSVSite/Views/RND/ImageFadeOut.cshtml
@{
    ViewBag.Title = "ImageFadeOut";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<h2>ImageFadeOut</h2>

<div id="dvLoading"></div>


<style type="text/css">
    
#dvLoading

{

   background:#000 url(images/loader.gif) no-repeat center center;
   height: 100px;
   width: 100px;
   position: fixed;
   z-index: 1000;
   left: 50%;
   top: 50%;
   margin: -25px 0 0 -25px;
}


</style>


    <script>

$(window).load(function(){

  $('#dvLoading').fadeOut(2000);

});

</script>

</script>